### PR TITLE
do_build.sh: re-enable package tree hardlinks, saving ~1.5GB per build

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by brendank310** [comment]
+1

**Comment by eric-ch** [comment]
+1

**Comment by jean-edouard** [comment]
This PR is included in http://openxt.ainfosec.com:81/builds/master/ext-dev-284-master/
The build logs show all packages got hardlinked, except for the metadata, as expected.
Once installed, opkg work fine. +1 :)

**Comment by rossphilipson** [comment]
Everyone seems to think this is good stuff and it has been tested. I will merge in a while.

**Pull request merged**
