### PR TITLE
build-scripts: fix user ID on known_hosts files inside the containers

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
Makes sense, will merge soon. While on the topic of user ids, next time you make a minor fix can you change the git mirror location name from /home/git? Creating a user id named "git" is not all that uncommon if you are hosting git repos :)

**Comment by jean-edouard** [comment]
Ack. However, if you want to host additional git repos on your build machine, they should go into that same directory, since I don't think you can run multiple git services on the same machine, at least not on the default port.

**Comment by rossphilipson** [comment]
I am not sure what you mean by running multiple git services. Are your scripts installing and running a git service?

Anyway that doesn't matter to me - I only use ssh.

**Comment by jean-edouard** [comment]
Yes they do.

And yes, if you use ssh, what I said doesn't matter.

**Pull request merged**
