### PR TITLE
windows: mkbuildmachine: add support for using a mirror

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-507

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
It is kind of confusing how you have the full URLs to the file and in addition the package (file) names in a separate list. It might be clearer if the URLs were the base part that the mirror overrides.

**Comment by jean-edouard** [comment]
I agree, but sometimes the name given to the downloaded file is not the same as the name in the URL, and I didn't want to mess with more than I had to...
Maybe as a separate pull request?

**Comment by rossphilipson** [comment]
Oh well if that is the case then it is fine. I don't want to bust stuff just for something small like that. Disregard...

**Comment by rossphilipson** [comment]
Will merge soon...

**Pull request merged**
