### PR TITLE
STABLE-6: OXT-804: Linux tools packaging & installation.

### PR DESCRIPTION
**Pull request by eric-ch**
Xen 4.3.4 sources require a configure which this hack will not handle well. Fortunately, since the tools only package libxenstore and xenstore-utils, it can be tricked with an empty ```config/Tools.mk``` to build using the usual dependencies.

Use openxt-v4v ```make headers_install``` for headers, avoiding other failures.
Use ```python2``` with Xen's build system.
Remove absolute path from commands in postinst (not that the warnings where a big issue) and overrride a couple of warning to make the output less ugly.

Testing it was not a nice process, hence the changes to have the package handle compilation failures and errors in post-install a little better and make these easier to recover from.

Package installation tested on Ubuntu 16.10 and Centos 7.

### CODE REVIEW

**Comment by eric-ch** [comment]
The tickets assigned to this PR will require https://github.com/OpenXT/pv-linux-drivers/pull/42 as well. Both PR should be considered interdependent.

**Comment by eric-ch** [comment]
The last commit also relates to linked tickets: OXT-964 OXT-982 OXT-983

**Comment by eric-ch** [comment]
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/714

**Comment by rossphilipson** [comment]
Tested with above build. Successfully installed Ubuntu 16.10, CentOS 7 and Debian 8 (all 64b). Fedora 24 did not work but for a different reason (will update ticket). LGTM, merging soon.

**Pull request merged**
