### PR TITLE
OXT-1327: HVM NDVM

### PR DESCRIPTION
**Pull request by jandryuk**
Theses are the changes to build and package HVM NDMVs.

I've tested the do_build.sh changes.  The build-scripts changes, https://github.com/OpenXT/openxt/commit/29cf3fc6eb9931c6fed3a93777e6a71e395e4187, are untested, so review and test is appreciated.

Depends:
https://github.com/OpenXT/xenclient-oe/pull/912
https://github.com/OpenXT/xsm-policy/pull/20
https://github.com/OpenXT/manager/pull/116

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1544

**Comment by jandryuk** [comment]
Remember to`db-write /xenmgr/ndvm-mode hvm` and reboot to try out hvm ndvms.

**Comment by eric-ch** [comment]
Build [$1558](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1558)

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1562

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Pull request merged**
