### PR TITLE
build-scripts: remove architecture info from output files

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-1554
OXT-1552

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
do_build.sh changes untested, will exclude on request.

**Comment by jandryuk** [comment]
I'll test out the do_build.sh changes for you.

**Comment by jandryuk** [comment]
I built and installed an OTA package successfully.  Thanks.

Note to dirty builders: Clean out `build-output/*/{raw,repository/packages.main}/*.i686.*` files so you don't package up the old ones.

**Comment by jean-edouard** [comment]
Nice, thanks! stable-9 PR open: https://github.com/OpenXT/openxt/pull/347

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6513

**Pull request merged**
