### PR TITLE
build-scripts: openxt prefix was dropped from the v4v deb package name

### PR DESCRIPTION
**Pull request by Jafaral**
Signed-off-by: Jafar Al-Gharaibeh <jafar@atcorp.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
LGTM, stable-8 seems to suffer from the same issue, would you mind PR-ing a cherry-pick of this into stable-8?

**Comment by eric-ch** [comment]
+1, this got removed with https://github.com/OpenXT/v4v/pull/37.

**Comment by Jafaral** [comment]
@jean-edouard, sure, will do

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
