### PR TITLE
STABLE-6: Only allow upgrades from 6.0.0

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-1188

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by MagOXT** [comment]
+1

**Comment by eric-ch** [comment]
LGTM.

**Comment by richpersaud** [comment]
We should not be dropping support for upgrade from 5.0.1.

**Comment by eric-ch** [comment]
Community call 08/24/2017, it was discussed that 5.0.1 should make it back to the list.

**Comment by jean-edouard** [comment]
"You asked to amend the most recent commit, but doing so would make it empty." indeed :)
Closing.

**Pull request closed without merging**
