### PR TITLE
STABLE-7: OXT-1094: config: Xen 4.6.5 micro-upgrade

### PR DESCRIPTION
**Pull request by eric-ch**
Upgrade common-config to use the latest Xen micro release.

### CODE REVIEW

**Comment by eric-ch** [comment]
https://github.com/OpenXT/xenclient-oe/pull/632

**Comment by rossphilipson** [comment]
Building here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/854

**Comment by rossphilipson** [comment]
Disregard that other build, built here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/856

**Comment by rossphilipson** [comment]
Tested, LGTM, will merge with RM signoff.

**Pull request merged**
