### PR TITLE
Stable 6 build fix for OXT-692

### PR DESCRIPTION
**Pull request by dpsmith**
This PR adds the packages called out in OXT-692, cleans up some mixed whitespace, and adjusts how build.sh gets passed into the build container.

### CODE REVIEW

**Comment by jean-edouard** [comment]
- This PR addresses multiple things, it should be split into multiple PRs, especially since I don't think some of the changes here belong to stable-6 at this point (I'd say we just want the missing packages).
- Most, if not all, the changes in this PR apply to the master branch, so the PRs should be submitted against master first, then cherry-picked into stable-6 (see https://openxt.atlassian.net/wiki/display/BS/Branches%2C+Tags+and+Releases)

**Comment by dpsmith** [comment]
I would give you that commit f5acf94 is a bit unrelated, but does not apply to master as the mix match of whitespace in stable-6 version is not in the master version (though it does have its own set). The last commit 27f0a65 does apply to both but is relevant here as cat-ing a script into an attached tty is unreliable. I have this change in progress to master, but it is included with additional refactoring that would not apply to

**Comment by jean-edouard** [comment]
Please do a PR for https://github.com/OpenXT/openxt/pull/172/commits/4022501035cd914d4cb5b9b83b94e4f8c3200685 in master and a cherry-pick PR in stable-6. It looks ok, just not sure I like the `-q`...

https://github.com/OpenXT/openxt/pull/172/commits/27f0a65eaf15759797a280a1c24eb2f1cf593575 is a big change. It makes sense and I already have it in a personal work branch. It makes things look better, but it is incompatible with programs that "eat" stdin like `apt-get`.
If you have an example of a problem that this commit fixes, please PR it in master and cherry-pick PR in stable-6.

**Comment by rossphilipson** [comment]
Closing this for now. We can get this into 6.1 if desired and master (7.0)

**Pull request closed without merging**
