### PR TITLE
Build scripts and build daemon improvements

### PR DESCRIPTION
**Pull request by jean-edouard**
I've been working on:
- Adding Windows to the build scripts
- Fixing the build daemon for Windows
- Automating the build daemon installation
- Various smaller fixes

All that work is piling up in my fork, and since things are in pretty good shape right now, I would like to get it all integrated into OpenXT.

OXT-507

### CODE REVIEW

**Comment by rossphilipson** [comment]
I will setup a clean Jessie 64 and try it all from the ground up.

**Comment by jean-edouard** [comment]
Please note that I just added a commit to this pull request, after finding a small issue in mkbuildserver.ps1

**Comment by jean-edouard** [comment]
And another one for mkbuildmachine.ps1... Sorry for the sloppy pull request.

**Comment by rossphilipson** [comment]
Tested. Discovered some interesting failure modes when I did things wrong. Reported all that to @jean-edouard. It all worked in the end and I got a Windows VM started and installed. Merging soon.

**Pull request merged**
