### PR TITLE
Clean up default config file

### PR DESCRIPTION
**Pull request by dpquigl2**
This commit is to be paired with the corresponding pull request for the
xenclient-oe repository which pushes the configuration data into the
recipes themselves.

OXT-308

Signed-off-by: David Quigley <drquigl@tycho.nsa.gov>

### CODE REVIEW

**Comment by jean-edouard** [comment]
LGTM, just one question, why did you move some `ASNEEDED`s but not all of them?

**Comment by dpquigl2** [comment]
Some of the ASNEEDED statements would have required me to create new bbappend files just for them.

**Comment by jean-edouard** [comment]
Maybe for 1 or 2, but most already have a recipe in xenclient-oe...

**Comment by jean-edouard** [comment]
I checked, and none of them seem to require a new bbappend, as they all have recipes bits in xenclient-oe already.

**Comment by dpquigl2** [comment]
I can amend the ASNEEDED statements to cover them all. I'll work on that this week but I'm in and out of work for family reasons.

**Comment by jean-edouard** [comment]
Bump

**Comment by dpquigl2** [comment]
Sorry about the delay. I was moved onto a short 30 day project about a month ago and am just getting back to my desk now. I will look into these and updating them soon. I'm working on forward porting some xen modifications I have at the moment which has taken a priority.

**Comment by rossphilipson** [comment]
We don't really have any guidance spelled out on how to deal with situations where PRs get left open for very long periods of time without any activity. I feel as maintainers we should be able to address them by closing them after said long period of time and having given ample chances for the author to address them. We are really trying hard not to have PRs languish forever or pile up. Ultimately the PR can be re-opened anyway so nothing is lost.

If anyone would like to comment on this approach, please do. I am inclined to close this one out.

**Comment by dpquigl2** [comment]
I'm ok with that. Unfortunately work has made it so I can't go back to finishing this off for now. The commits are in my tree and if anyone wants to take them and finish it up thats fine with me but unfortunately I have several things that have to be fixed on our end at the moment.

**Comment by rossphilipson** [comment]
@dpquigl2  we have decided out of the kindness of our hearts to go ahead and finish this one for you :)

Actually it is a good PR just incomplete so we want it. Just note we don't want to set a precedent here - doing this is a one off. Jed is going to do his own 2 PRs based on this. Please close out your 2 PRs when you have a chance.

**Comment by dpquigl2** [comment]
Thank you for finishing this one up. I kept trying to come back to it and every time I started something else came up which was "more important". Ill close my two PRs

**Pull request closed without merging**
