### PR TITLE
build-scripts: fix layer files for order and build overrides

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
Building here along with my OCaml updates:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/653

**Comment by rossphilipson** [comment]
Built here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/654

So it can be merged.

**Comment by jean-edouard** [comment]
Works fine, merging soon.

**Comment by rossphilipson** [comment]
I will merge since you posted it - for consistency.

**Pull request merged**
