### PR TITLE
build-scripts: add Linux tools install scripts

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-702

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Replaces https://github.com/OpenXT/openxt/pull/232 and https://github.com/OpenXT/openxt/pull/237

**Comment by jean-edouard** [comment]
@dpsmith want this in stable-7?

**Comment by dpsmith** [comment]
Sure

**Comment by jean-edouard** [comment]
https://github.com/OpenXT/openxt/pull/248

**Comment by rossphilipson** [comment]
Merging soon.

**Pull request merged**
