### PR TITLE
local.conf-dist: inherit xenclient-customtask

### PR DESCRIPTION
**Pull request by cjp256**
OXT-455

Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Thank you, merging soon.
Do you by any chance know the difference between local.conf-dist and local.conf? Just curious.

**Comment by rossphilipson** [comment]
Yea I worked around the issue by putting the value in local.conf and did not need to add it to local.conf-dist. I am curious what the latter file is too.

**Comment by cjp256** [comment]
@jean-edouard @rossphilipson local.conf is generated from local.conf-dist (do_build.sh/setup_build).

**Comment by jean-edouard** [comment]
Oh yeah, sure, that makes sense. Thanks! Merging.

**Pull request merged**
