### PR TITLE
build-scripts: install Linux tools install scripts to tools iso

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-702

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/710

**Comment by rossphilipson** [comment]
Is this PR missing some new scripts?

**Comment by rossphilipson** [comment]
Never mind, I see there is another PR that adds the scripts:

https://github.com/OpenXT/openxt/pull/232

**Comment by rossphilipson** [comment]
This is not working, see ticket.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/756

**Comment by jean-edouard** [comment]
Replaced by https://github.com/OpenXT/openxt/pull/247, closing.

**Pull request closed without merging**
