### PR TITLE
Remove recipes versions from local.conf

### PR DESCRIPTION
**Pull request by eric-ch**
Use the DISTRO=openxt-main instead (see relevant commit in
xenclient-oe.git).

See https://github.com/OpenXT/xenclient-oe/pull/181 for related changes in xenclient layer (xenclient-oe.git).

### CODE REVIEW

**Comment by cjp256** [comment]
+1, these changes will also make the OE uprev easier.

Building now.

**Comment by cjp256** [comment]
LGTM

**Comment by transpute** [comment]
Can we use a common JIRA ticket for OE cleanup PRs related to the uprev?

**Comment by eric-ch** [comment]
I think there will be more than one cleaning PR along the way. Should we even consider to make an epic to regroup all of those?

**Comment by transpute** [comment]
Any level of tracking (ticket, tickets, epic) would be better than no tracking.  The Qemu uprev had an epic.  Since this is such a big move (years of OE changes), tickets can help to group related changes/PRs.

**Comment by eric-ch** [comment]
Just created https://openxt.atlassian.net/browse/OXT-426.
I'll try to keep it up to date, starting with this PR (although it has already been merged).

**Pull request merged**
