### PR TITLE
Add dual-signing thumbprints to configuration sample

### PR DESCRIPTION
**Pull request by pearsonk**
Signed-off-by: Kevin Pearson <kevin.pearson.4@us.af.mil>

### CODE REVIEW

**Comment by pearsonk** [comment]
PR cluster for this to work:
https://github.com/OpenXT/openxt/pull/80
https://github.com/OpenXT/xc-windows/pull/20
https://github.com/OpenXT/win-tools/pull/7
https://github.com/OpenXT/msi-installer/pull/9

This allows for dual-signing of drivers and packages (minus .msi which doesn't support append) allowing for signatures of SHA1 and SHA256. This also requires specification of match certificates by thumbprint, as having two sets of keys with the same CN would otherwise cause conflicts and "best-guess" by signtool regarding which one to use.

**Comment by jean-edouard** [comment]
This means everybody will have to compute the sha1 of their certificate, edit sample-config.xml and fix <SHA1Thumb>? In that case, could maybe winbuild-prepare.ps1 take care of it, for automation purposes?

**Comment by rossphilipson** [comment]
I agree with Jed on that. Also, can we get some testing instructions for all this too?

**Comment by pearsonk** [comment]
Actually, the thumbprint of the certificate is something you can simply copy out using certmgr.msc as it's one of the fields there. Adding some logic to winbuild-prepare.ps1 shouldn't be difficult to add to ease the transition. I'll close these until I can get that done.

**Pull request closed without merging**
