### PR TITLE
OXT-1187: xen: upgrade to 4.6.6

### PR DESCRIPTION
**Pull request by eric-ch**
See release notes:
https://www.xenproject.org/downloads/xen-archives/xen-46-series/xen-466.html

Depends on: https://github.com/OpenXT/xenclient-oe/pull/724

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1024

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1034

**Comment by jean-edouard** [comment]
Merging soon.

**Comment by dpsmith** [comment]
Would appreciate if a stable-7 version could be submitted, thanks!

**Comment by eric-ch** [comment]
@spsmith https://github.com/OpenXT/openxt/pull/259 & https://github.com/OpenXT/xenclient-oe/pull/727. The version affected in the ticket has been set to 7.0.0 as well.

**Pull request merged**
