### PR TITLE
windows: mkbuildmachine: cygwin: add proxy support and wget package

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-55
OXT-507

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
@pearsonk can you test this? You entered the ticket long ago so it seems reasonable you have an environment where you could. We have no way of doing it here without setting up proxies etc.

**Comment by rossphilipson** [comment]
@pearsonk what should we do with this PR for OXT-55?

**Comment by pearsonk** [comment]
Alternative approach (because I forgot to actually test with this PR) at https://github.com/OpenXT/openxt/pull/155

Both will work just fine, 155 simply uses the system proxy settings as opposed to a script flag

**Comment by jean-edouard** [comment]
The approach in #155 makes a lot more sense to me, closing soon.

**Pull request closed without merging**
