### PR TITLE
[windows] Remove all win-tools and add a new user agent.

### PR DESCRIPTION
**Pull request by rossphilipson**
OXT-563

This allows us to remove the v4v services for guests in dom0 and
close the viptables ports. The only bit left in win-tools that is
needed is the resoultion agent which will be in the new user agent.

Signed-off-by: Ross Philipson <philipsonr@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
Goes with:
https://github.com/OpenXT/msi-installer/pull/11
https://github.com/OpenXT/xc-windows/pull/28

**Comment by rossphilipson** [comment]
Tested this custom Windows build here:
http://openxt.ainfosec.com/builds/windows-custom/22/

**Comment by smeisner** [comment]
RE: OpenXT/xc-windows#28:

Normalize indentation!! Mix of spaces and tabs must be fixed. Makes code difficult to read at times.

OxtService/OxtService.rc:78 : Add company name?
OxtService/OxtServiceTest/OxtServiceTest.cpp:134 : Can we have an appropriate comment? Maybe include the value of hr and indicate what failed.
OxtService/poweropts.c:185 : Entry points are loaded, but never used. If they fail to load, this casues an error.
                             Should the commented out MessageBox calls be replaced with PowerDisplayError calls?

Other than the massive amount of COM and security code, and what's mentioned above, it looks good.

+1 on the other commits.

**Comment by rossphilipson** [comment]
I fixed all the formatting issues and company name. On the other subjects...

OxtService/OxtServiceTest/OxtServiceTest.cpp
I did not really do anything with the tests other than copy them over. They need a bunch of work to even be functional. I would rather create a ticket and fix them up later. Since nothing runs them currently even in win-tools.git there is no regression here. Would that be acceptable?

OxtService/poweropts.c:
PowerDisplayError just has commented out message boxes too. This is of course because the thing is running as a service. The right way to do (which should have been done in the first place) is to write the errors to the event log. Again there is no regression here so I would like to put the work to enhance that in a ticket for later. Is that acceptable?

**Comment by jean-edouard** [comment]
@smeisner, if that works for you, I suggest we merge all 3 PRs.

**Comment by smeisner** [comment]
ack

**Comment by jean-edouard** [comment]
Thanks, merging soon.

**Comment by rossphilipson** [comment]
https://openxt.atlassian.net/browse/OXT-599
https://openxt.atlassian.net/browse/OXT-600

**Pull request merged**
