### PR TITLE
do_build: drop support for arbitrary extra repository

### PR DESCRIPTION
**Pull request by cjp256**
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Why?

**Comment by cjp256** [comment]
Why carry an empty layer that provides no value?  Cleanup.  At very least it should be renamed, but what's the point. It's easy enough to add a custom layer, if desired.

**Comment by jean-edouard** [comment]
I guess that makes sense, I'll test and merge soon.

**Comment by jean-edouard** [comment]
`./do_build.sh -s setupoe,initramfs` ran fine with this patch, that's enough for me, merging.

**Comment by jean-edouard** [comment]
This breaks force_rebuild and makeclean, reverting, please fix.

**Pull request merged**
