### PR TITLE
build-scripts: add options to not setup/build some containers/VMs

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-507

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
That LGTM - fan of getopts though I usually like to see it and usage() at the bottom of scripts. No biggie though.

**Comment by jean-edouard** [comment]
Added a commit to fix the indentation.

**Comment by jean-edouard** [comment]
PR rebased

**Comment by jean-edouard** [comment]
This is included in a more recent PR, closing.

**Pull request closed without merging**
