### PR TITLE
Dynamically determine the rootfs sizes during build time.

### PR DESCRIPTION
**Pull request by crogers1**
Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
This PR references https://github.com/OpenXT/installer/pull/6

At build time, we also need to determine dom0 rootfs size dynamically.  Currently, we explicitly set the size for all rootfs's.  This is undesirable for two reasons: A) As components are added, we can trigger a build failure because the rootfs is too small, and B) we waste space by not setting the size to exactly the size of the rootfs being built (one size does NOT fit all in this scenario).  Therefore, dom0 (and by extension the other rootfs's) should be sized dynamically to avoid both of the above reasons.

**Comment by jean-edouard** [comment]
Any chance those very long sequences of commands could be multi-line? I know you're following what's there already, but it is pretty unreadable...

**Comment by crogers1** [comment]
Made the commands multi-lined, doesn't seem to change the functionality.

**Comment by crogers1** [comment]
Bash always rounds down, so if the result is even, actual size > rounded size, unless there was no rounding performed.  So yea in most cases we're losing precision if the result is even.

**Comment by jean-edouard** [comment]
I ... don't get it

**Comment by crogers1** [comment]
We discussed this offline already but just to clarify, the vhd size has to be a multiple of 2 MB or it will throw an error, that's the reason for the even/odd logic.

**Comment by crogers1** [comment]
We good to merge?

**Comment by jean-edouard** [comment]
Will merge soon.

**Comment by cjp256** [comment]
I have 61M of free space in my dom0 image, is this expected?

**Pull request merged**
