### PR TITLE
build-scripts: add modular layer support and move xenclient-oe to one

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-507

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
LGTM, will merge soon.

**Comment by rossphilipson** [comment]
I think 14 days fits the definition of soon, merging.

**Comment by dozylynx** [comment]
This change is proving problematic in my build, as it results in the xenclient-oe repo missing from the build/repos directory followed by failure.

Where are the .layer files meant to live? It looks like the `cat` command expects them in the current working directory, but setup.sh has no reference to them, so isn't placing them into `$BUILD_USER_HOME`.

If I copy the `01-xenclient-oe.layer` file into `$BUILD_USER_HOME`, it gets further and then dies when looking for the meta-intel repo.

**Comment by eric-ch** [comment]
@dozylynx Regarding meta-intel there is a known issue with the build-scripts  (https://openxt.atlassian.net/browse/OXT-743). I think https://github.com/eric-ch/openxt/tree/oxt-743 should fix it, but I am having a hard time testing it, if you can have a go it would be awesome.

**Comment by dozylynx** [comment]
@eric-ch :  Good to know, thanks. I will take a look at your changes once I've got a build pushed through.
For now, I've hacked build-scripts/oe/build.sh to clone meta-intel into the right place but now the loop over the layer contents is only building the first of the series:
ie.
`"xenclient-dom0         xenclient-initramfs                 cpio.gz"`
and not proceeding through the rest, so I'm pushing it past that by hand at the moment.

**Comment by jean-edouard** [comment]
Thanks for reporting the issues you found in the build scripts.
They are definitely broken right now, even without Eric's changes.
They need some love, but I'm currently busy with other stuff.
I'll try to have a look next week.

**Pull request merged**
